=== Kyoril/mmo-data/Interface/GlueUI/Ui.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://mmo-dev.net/ui"
    elementFormDefault="qualified"
    xmlns="http://mmo-dev.net/ui"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="FrameRendererType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DefaultRenderer" />
      <xs:enumeration value="ButtonRenderer" />
      <xs:enumeration value="CheckboxRenderer" />
      <xs:enumeration value="TextFieldRenderer" />
      <xs:enumeration value="ModelRenderer" />
      <xs:enumeration value="WorldRenderer" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="AnchorPointType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LEFT" />
      <xs:enumeration value="TOP" />
      <xs:enumeration value="RIGHT" />
      <xs:enumeration value="BOTTOM" />
      <xs:enumeration value="H_CENTER" />
      <xs:enumeration value="V_CENTER" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TilingType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NONE" />
      <xs:enumeration value="HORZ" />
      <xs:enumeration value="VERT" />
      <xs:enumeration value="BOTH" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HorzAlignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LEFT" />
      <xs:enumeration value="CENTER" />
      <xs:enumeration value="RIGHT" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="VertAlignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TOP" />
      <xs:enumeration value="CENTER" />
      <xs:enumeration value="BOTTOM" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ScriptFileType">
    <xs:attribute name="file" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ScriptBlockType">
    <xs:simpleContent>
      <xs:extension base="xs:string" />
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="FontType">
    <xs:attribute name="name" use="required" type="xs:string" />
    <xs:attribute name="file" use="required" type="xs:string" />
    <xs:attribute name="size" use="required" type="xs:decimal" />
    <xs:attribute name="outline" use="optional" type="xs:decimal" />
    <xs:attribute name="shadowX" use="optional" type="xs:decimal" />
    <xs:attribute name="shadowY" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="PropertyType">
    <xs:attribute name="name" use="required" type="xs:string" />
    <xs:attribute name="value" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="PropertyValueType">
    <xs:attribute name="property" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="InsetType">
    <xs:attribute name="all" use="optional" type="xs:decimal" />
    <xs:attribute name="left" use="optional" type="xs:decimal" />
    <xs:attribute name="top" use="optional" type="xs:decimal" />
    <xs:attribute name="right" use="optional" type="xs:decimal" />
    <xs:attribute name="bottom" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="AreaComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Inset" type="InsetType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="BorderComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="texture" use="required" type="xs:string" />
    <xs:attribute name="borderSize" use="optional" type="xs:decimal" />
    <xs:attribute name="topSize" use="optional" type="xs:decimal" />
    <xs:attribute name="leftSize" use="optional" type="xs:decimal" />
    <xs:attribute name="rightSize" use="optional" type="xs:decimal" />
    <xs:attribute name="bottomSize" use="optional" type="xs:decimal" />
    <xs:attribute name="tint" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ImageComponentType">
    <xs:sequence minOccurs="0" maxOccurs="2">
      <xs:choice>
        <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
        <xs:element name="PropertyValue" type="PropertyValueType" minOccurs="0" maxOccurs="1" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="texture" use="optional" type="xs:string" />
    <xs:attribute name="tint" use="optional" type="xs:string" />
    <xs:attribute name="tiling" use="optional" type="TilingType" />
  </xs:complexType>

  <xs:complexType name="TextComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="color" use="optional" type="xs:string" />
    <xs:attribute name="horzAlign" use="optional" type="HorzAlignType" />
    <xs:attribute name="vertAlign" use="optional" type="VertAlignType" />
    <xs:attribute name="wrap" use="optional" type="xs:boolean" />
  </xs:complexType>

  <xs:complexType name="ImagerySectionType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="BorderComponent" type="BorderComponentType" />
        <xs:element name="ImageComponent" type="ImageComponentType" />
        <xs:element name="TextComponent" type="TextComponentType" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="SectionType">
    <xs:attribute name="section" use="required" type="xs:string" />
    <xs:attribute name="color" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="LayerType">
    <xs:sequence>
      <xs:element name="Section" maxOccurs="unbounded" minOccurs="1" type="SectionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="StateImageryType">
    <xs:sequence>
      <xs:element name="Layer" type="LayerType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="VisualType">
    <xs:sequence minOccurs="0">
      <xs:choice maxOccurs="unbounded">
        <xs:element name="ImagerySection" type="ImagerySectionType" />
        <xs:element name="StateImagery" type="StateImageryType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AbsDimensionType">
    <xs:attribute name="x" use="optional" type="xs:decimal" />
    <xs:attribute name="y" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="SizeType">
    <xs:sequence>
      <xs:element name="AbsDimension" type="AbsDimensionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PositionType">
    <xs:sequence>
      <xs:element name="AbsDimension" type="AbsDimensionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AnchorType">
    <xs:attribute name="point" use="required" type="AnchorPointType" />
    <xs:attribute name="relativePoint" use="optional" type="AnchorPointType" />
    <xs:attribute name="relativeTo" use="optional" type="xs:string" />
    <xs:attribute name="offset" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="AreaType">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Size" type="SizeType" />
        <xs:element name="Position" type="PositionType" />
        <xs:element name="Anchor" type="AnchorType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="EventsType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:any processContents="lax" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ScriptsType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="OnClick" type="ScriptBlockType" />
      <xs:element name="OnLoad" type="ScriptBlockType" />
      <xs:element name="OnUpdate" type="ScriptBlockType" />
      <xs:element name="OnTabPressed" type="ScriptBlockType" />
      <xs:element name="OnEnterPressed" type="ScriptBlockType" />
      <xs:element name="OnSpacePressed" type="ScriptBlockType" />
      <xs:element name="OnEscapePressed" type="ScriptBlockType" />
      <xs:element name="OnTextChanged" type="ScriptBlockType" />
      <xs:element name="OnShow" type="ScriptBlockType" />
      <xs:element name="OnHide" type="ScriptBlockType" />
      <xs:element name="OnEnter" type="ScriptBlockType" />
      <xs:element name="OnLeave" type="ScriptBlockType" />
      <xs:element name="OnDrag" type="ScriptBlockType" />
      <xs:element name="OnDrop" type="ScriptBlockType" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="FrameType">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Property" type="PropertyType" />
        <xs:element name="Visual" type="VisualType" />
        <xs:element name="Area" type="AreaType" />
        <xs:element name="Events" type="EventsType" />
        <xs:element name="Scripts" type="ScriptsType" />
        <xs:element name="Frame" type="FrameType" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="type" type="xs:string" use="optional" />
    <xs:attribute name="renderer" type="FrameRendererType" use="optional" />
    <xs:attribute name="inherits" type="xs:string" use="optional" />
    <xs:attribute name="parent" type="xs:string" use="optional" />
    <xs:attribute name="setAllPoints" type="xs:boolean" use="optional" />
    <xs:attribute name="id" type="xs:int" use="optional" />
  </xs:complexType>

  <xs:element name="Frame" type="FrameType" />

  <xs:element name="UiLayout">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Script" minOccurs="0" maxOccurs="unbounded" type="ScriptFileType" />
        <xs:element name="Font" minOccurs="0" maxOccurs="unbounded" type="FontType" />
        <xs:element ref="Frame" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Kyoril/mmo-data/Interface/GameUI/BugReporter/BugReporter.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="BugReporter.lua" />

	<!-- The bug report dialog: generic, or about one item / spell / creature / quest / aura / object. -->
	<Frame name="BugReportFrame" parent="GameParent" renderer="DefaultRenderer">
		<Property name="Visible" value="False" />

		<Visual>
			<ImagerySection name="Background">
				<BorderComponent texture="Interface/GameUI/Alestia/WindowPanel.htex" borderSize="32" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
		</Visual>

		<Area>
			<Size><AbsDimension x="1200" y="1000" /></Size>
			<Anchor point="H_CENTER" />
			<Anchor point="V_CENTER" offset="-80" />
		</Area>

		<!-- Child 0: title bar with close button (wired by SidePanel_OnLoad). -->
		<Frame name="BugReportTitleBar" inherits="TitleBar">
			<Property name="Text" value="BUGREPORT_TITLE" />
			<Area>
				<Anchor point="TOP" offset="24" />
				<Anchor point="LEFT" offset="24" />
				<Anchor point="RIGHT" offset="-24" />
			</Area>
		</Frame>

		<Frame name="BugReportSubjectIcon" renderer="DefaultRenderer">
			<Property name="Icon" />
			<Property name="Clickable" value="false" />
			<Visual>
				<ImagerySection name="Well">
					<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlackSmall.htex" borderSize="11" />
				</ImagerySection>
				<ImagerySection name="Image">
					<ImageComponent>
						<Area><Inset all="12" /></Area>
						<PropertyValue property="Icon" />
					</ImageComponent>
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Well" />
						<Section section="Image" />
					</Layer>
				</StateImagery>
			</Visual>
			<Area>
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="BugReportTitleBar" offset="24" />
				<Anchor point="LEFT" offset="48" />
				<Size><AbsDimension x="128" y="128" /></Size>
			</Area>
		</Frame>

		<Frame name="BugReportPrompt" inherits="TextSmall">
			<Property name="Text" value="BUGREPORT_PROMPT_GENERIC" />
			<Property name="VertAlign" value="CENTER" />
			<Area>
				<Anchor point="TOP" relativeTo="BugReportSubjectIcon" />
				<Anchor point="LEFT" relativePoint="RIGHT" relativeTo="BugReportSubjectIcon" offset="32" />
				<Anchor point="RIGHT" offset="-48" />
				<Size><AbsDimension y="128" /></Size>
			</Area>
		</Frame>

		<Frame name="BugReportCommentField" inherits="GameTextField">
			<Property name="AcceptsTab" value="False" />
			<Property name="MultiLine" value="True" />
			<Property name="VertAlign" value="TOP" />
			<Area>
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="BugReportSubjectIcon" offset="24" />
				<Anchor point="LEFT" offset="48" />
				<Anchor point="RIGHT" offset="-48" />
				<Anchor point="BOTTOM" offset="-200" />
			</Area>
			<Scripts>
				<OnTextChanged>
					return function(this)
						BugReportCommentField_OnTextChanged(this);
					end
				</OnTextChanged>
				<OnEscapePressed>
					return function(this)
						BugReportFrame_Close();
					end
				</OnEscapePressed>
			</Scripts>
		</Frame>

		<Frame name="BugReportCounter" inherits="TextSmall">
			<Property name="HorzAlign" value="RIGHT" />
			<Property name="VertAlign" value="CENTER" />
			<Property name="TextColor" value="FFAAAAAA" />
			<Area>
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="BugReportCommentField" offset="8" />
				<Anchor point="RIGHT" offset="-48" />
				<Size><AbsDimension x="300" y="48" /></Size>
			</Area>
		</Frame>

		<Frame name="BugReportStatus" inherits="TextSmall">
			<Property name="VertAlign" value="CENTER" />
			<Property name="TextColor" value="FFFFFFFF" />
			<Area>
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="BugReportCommentField" offset="8" />
				<Anchor point="LEFT" offset="48" />
				<Anchor point="RIGHT" relativePoint="LEFT" relativeTo="BugReportCounter" offset="-16" />
				<Size><AbsDimension y="48" /></Size>
			</Area>
		</Frame>

		<Frame name="BugReportSubmitButton" inherits="GlueButton">
			<Property name="Text" value="BUGREPORT_SUBMIT" />
			<Area>
				<Anchor point="BOTTOM" offset="-40" />
				<Anchor point="H_CENTER" />
				<Size><AbsDimension x="360" y="80" /></Size>
			</Area>
			<Scripts>
				<OnClick>
					return function(this)
						BugReportFrame_Submit();
					end
				</OnClick>
			</Scripts>
		</Frame>

		<Scripts>
			<OnLoad>
				return function(this)
					BugReportFrame_OnLoad(this);
				end
			</OnLoad>
			<OnUpdate>
				return function(this, deltaTime)
					BugReportFrame_OnUpdate(this, deltaTime);
				end
			</OnUpdate>
			<OnHide>
				return function(this)
					BugReportFrame_OnHide(this);
				end
			</OnHide>
		</Scripts>
	</Frame>

	<!-- "Report" button in the quest log footer, next to Abandon. -->
	<Frame name="QuestLogReportButton" inherits="GlueButton" parent="QuestLogFooter">
		<Property name="Text" value="BUGREPORT_REPORT_QUEST" />
		<Area>
			<Anchor point="BOTTOM" offset="-16" />
			<Anchor point="LEFT" offset="16" />
			<Size><AbsDimension x="300" y="64" /></Size>
		</Area>
		<Scripts>
			<OnClick>
				return function(this)
					BugReporter_ReportQuestLogSelection();
				end
			</OnClick>
		</Scripts>
	</Frame>
</UiLayout>

=== Kyoril/mmo-data/Interface/GameUI/AuraBar.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="AuraBar.lua" />

    <Frame name="AuraBar" parent="GameParent">
        <!-- Right offset keeps the aura rows clear of the whole top-right HUD column, not just
             the minimap: the quest tracker hangs below the minimap but is 560 wide (QuestTracker.xml),
             so it reaches further left than the 384 wide minimap. With the minimap collapsed the
             tracker rises next to the aura rows, and a smaller offset would put its heading on top
             of the first buff's duration label. 24 (tracker margin) + 560 (tracker) + 8 (gap) = 592. -->
        <Area>
			<Anchor point="TOP" offset="8" />
			<Anchor point="RIGHT" offset="-592" />
            <Size>
                <AbsDimension x="1024" y="256" />
            </Size>
        </Area>

        <!-- Buff (Positive Aura) Row -->
        <Frame name="BuffButton1" inherits="AuraBarButtonTemplate" id="1">
            <Area>
                <Anchor point="RIGHT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="BuffButton2" inherits="AuraBarButtonTemplate" id="2">
            <Area>
                <Anchor point="RIGHT" relativeTo="BuffButton1" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="BuffButton3" inherits="AuraBarButtonTemplate" id="3">
            <Area>
                <Anchor point="RIGHT" relativeTo="BuffButton2" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="BuffButton4" inherits="AuraBarButtonTemplate" id="4">
            <Area>
                <Anchor point="RIGHT" relativeTo="BuffButton3" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="BuffButton5" inherits="AuraBarButtonTemplate" id="5">
            <Area>
                <Anchor point="RIGHT" relativeTo="BuffButton4" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="BuffButton6" inherits="AuraBarButtonTemplate" id="6">
            <Area>
                <Anchor point="RIGHT" relativeTo="BuffButton5" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="BuffButton7" inherits="AuraBarButtonTemplate" id="7">
            <Area>
                <Anchor point="RIGHT" relativeTo="BuffButton6" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="BuffButton8" inherits="AuraBarButtonTemplate" id="8">
            <Area>
                <Anchor point="RIGHT" relativeTo="BuffButton7" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>

        <!-- Debuff (Negative Aura) Row -->
        <Frame name="DebuffButton1" inherits="AuraBarButtonTemplate" id="9">
            <Area>
                <Anchor point="RIGHT" offset="0" />
                <Anchor point="TOP" offset="164" />
            </Area>
        </Frame>
        
        <Frame name="DebuffButton2" inherits="AuraBarButtonTemplate" id="10">
            <Area>
                <Anchor point="RIGHT" relativeTo="DebuffButton1" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="164" />
            </Area>
        </Frame>
        
        <Frame name="DebuffButton3" inherits="AuraBarButtonTemplate" id="11">
            <Area>
                <Anchor point="RIGHT" relativeTo="DebuffButton2" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="164" />
            </Area>
        </Frame>
        
        <Frame name="DebuffButton4" inherits="AuraBarButtonTemplate" id="12">
            <Area>
                <Anchor point="RIGHT" relativeTo="DebuffButton3" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="164" />
            </Area>
        </Frame>
        
        <Frame name="DebuffButton5" inherits="AuraBarButtonTemplate" id="13">
            <Area>
                <Anchor point="RIGHT" relativeTo="DebuffButton4" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="164" />
            </Area>
        </Frame>
        
        <Frame name="DebuffButton6" inherits="AuraBarButtonTemplate" id="14">
            <Area>
                <Anchor point="RIGHT" relativeTo="DebuffButton5" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="164" />
            </Area>
        </Frame>
        
        <Frame name="DebuffButton7" inherits="AuraBarButtonTemplate" id="15">
            <Area>
                <Anchor point="RIGHT" relativeTo="DebuffButton6" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="164" />
            </Area>
        </Frame>
        
        <Frame name="DebuffButton8" inherits="AuraBarButtonTemplate" id="16">
            <Area>
                <Anchor point="RIGHT" relativeTo="DebuffButton7" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="164" />
            </Area>
        </Frame>

        <Scripts>
            <OnLoad>
                return function(this)
                    AuraBar_OnLoad(this);
                end
            </OnLoad>
        </Scripts>
    </Frame>
    
</UiLayout>

=== Kyoril/mmo-data/Interface/GameUI/LootRollFrame.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="LootRollFrame.lua" />

	<!-- Compact text button using small border textures (borderSize=22, safe at 48px height) -->
	<Frame name="LootRollChoiceButtonTemplate" type="Button" renderer="ButtonRenderer">
		<Property name="Font" value="SmallLabelFont" />

		<Visual>
			<ImagerySection name="NormalFrame">
				<BorderComponent texture="Interface/GameUI/fg4_buttonSmall1_Up_result.htex" borderSize="22" />
			</ImagerySection>
			<ImagerySection name="HoveredFrame">
				<BorderComponent texture="Interface/GameUI/fg4_buttonSmall1_Over_result.htex" borderSize="22" />
			</ImagerySection>
			<ImagerySection name="PushedFrame">
				<BorderComponent texture="Interface/GameUI/fg4_buttonSmall1_Down_result.htex" borderSize="22" />
			</ImagerySection>
			<ImagerySection name="DisabledFrame">
				<BorderComponent texture="Interface/GameUI/fg4_buttonSmall2_Disabled_result.htex" borderSize="22" />
			</ImagerySection>
			<ImagerySection name="Caption">
				<TextComponent color="FFFFD100" horzAlign="CENTER" vertAlign="CENTER" />
			</ImagerySection>
			<ImagerySection name="HoveredCaption">
				<TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
			</ImagerySection>
			<StateImagery name="Normal">
				<Layer>
					<Section section="NormalFrame" />
					<Section section="Caption" />
				</Layer>
			</StateImagery>
			<StateImagery name="Hovered">
				<Layer>
					<Section section="HoveredFrame" />
					<Section section="HoveredCaption" />
				</Layer>
			</StateImagery>
			<StateImagery name="Pushed">
				<Layer>
					<Section section="PushedFrame" />
					<Section section="Caption" color="FFAAAAAA" />
				</Layer>
			</StateImagery>
			<StateImagery name="Disabled">
				<Layer>
					<Section section="DisabledFrame" />
					<Section section="Caption" color="AE888888" />
				</Layer>
			</StateImagery>
		</Visual>

		<Area>
			<Size><AbsDimension x="88" y="48" /></Size>
		</Area>
	</Frame>

	<!-- Roll item row: [Icon] [ItemName / Timer] [Need] [Greed] [Pass] -->
	<!-- Children order: 0=Icon, 1=Name, 2=Timer, 3=NeedButton, 4=GreedButton, 5=PassButton -->
	<Frame name="LootRollItemTemplate" renderer="DefaultRenderer">
		<Area>
			<Size><AbsDimension x="480" y="68" /></Size>
		</Area>

		<Visual>
			<ImagerySection name="Background">
				<BorderComponent texture="Interface/GameUI/fg4_borders_01_19.htex" borderSize="25" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
		</Visual>

		<!-- Child 0: Item icon -->
		<Frame name="Icon" renderer="DefaultRenderer">
			<Property name="Icon" value="" />

			<Area>
				<Position><AbsDimension x="10" y="10" /></Position>
				<Size><AbsDimension x="48" y="48" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Image">
					<ImageComponent tiling="NONE">
						<PropertyValue property="Icon" />
					</ImageComponent>
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Image" color="FFFFFFFF" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Image" color="AE888888" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

		<!-- Child 1: Item name -->
		<Frame name="Name" renderer="DefaultRenderer">
			<Property name="Font" value="SmallLabelFont" />

			<Area>
				<Position><AbsDimension x="66" y="8" /></Position>
				<Size><AbsDimension x="144" y="28" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Text">
					<TextComponent color="FFFFFFFF" horzAlign="LEFT" vertAlign="CENTER" />
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Text" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Text" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

		<!-- Child 2: Timer text -->
		<Frame name="Timer" renderer="DefaultRenderer">
			<Property name="Font" value="AuraTimeFont" />

			<Area>
				<Position><AbsDimension x="66" y="38" /></Position>
				<Size><AbsDimension x="100" y="22" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Text">
					<TextComponent color="FFAAAAAA" horzAlign="LEFT" vertAlign="CENTER" />
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Text" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Text" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

		<!-- Child 3: Need button -->
		<Frame name="NeedButton" type="Button" inherits="LootRollChoiceButtonTemplate">
			<Property name="Text" value="Need" />
			<Area>
				<Position><AbsDimension x="216" y="10" /></Position>
			</Area>
		</Frame>

		<!-- Child 4: Greed button -->
		<Frame name="GreedButton" type="Button" inherits="LootRollChoiceButtonTemplate">
			<Property name="Text" value="Greed" />
			<Area>
				<Position><AbsDimension x="308" y="10" /></Position>
			</Area>
		</Frame>

		<!-- Child 5: Pass button -->
		<Frame name="PassButton" type="Button" inherits="LootRollChoiceButtonTemplate">
			<Property name="Text" value="Pass" />
			<Area>
				<Position><AbsDimension x="400" y="10" /></Position>
			</Area>
		</Frame>
	</Frame>

	<!-- Invisible container: no background, positioned top-center -->
	<Frame name="LootRollFrame" parent="GameParent" renderer="DefaultRenderer">
		<Property name="Visible" value="false" />

		<Area>
			<Size><AbsDimension x="500" y="296" /></Size>
			<Anchor point="H_CENTER" />
			<Anchor point="TOP" offset="120" />
		</Area>

		<Scripts>
			<OnLoad>
				return function(self)
					LootRollFrame_OnLoad(self);
				end
			</OnLoad>
			<OnUpdate>
				return function(self, elapsed)
					LootRollFrame_OnUpdate(self, elapsed);
				end
			</OnUpdate>
		</Scripts>

		<Frame name="LootRollItem1" inherits="LootRollItemTemplate">
			<Area>
				<Anchor point="TOP" offset="4" />
				<Anchor point="H_CENTER" />
			</Area>
		</Frame>

		<Frame name="LootRollItem2" inherits="LootRollItemTemplate">
			<Area>
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="LootRollItem1" offset="4" />
				<Anchor point="H_CENTER" />
			</Area>
		</Frame>

		<Frame name="LootRollItem3" inherits="LootRollItemTemplate">
			<Area>
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="LootRollItem2" offset="4" />
				<Anchor point="H_CENTER" />
			</Area>
		</Frame>

		<Frame name="LootRollItem4" inherits="LootRollItemTemplate">
			<Area>
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="LootRollItem3" offset="4" />
				<Anchor point="H_CENTER" />
			</Area>
		</Frame>
	</Frame>
</UiLayout>
