=== Kyoril/mmo-data/Interface/GlueUI/Ui.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://mmo-dev.net/ui"
    elementFormDefault="qualified"
    xmlns="http://mmo-dev.net/ui"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="FrameRendererType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DefaultRenderer" />
      <xs:enumeration value="ButtonRenderer" />
      <xs:enumeration value="CheckboxRenderer" />
      <xs:enumeration value="TextFieldRenderer" />
      <xs:enumeration value="ModelRenderer" />
      <xs:enumeration value="WorldRenderer" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="AnchorPointType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LEFT" />
      <xs:enumeration value="TOP" />
      <xs:enumeration value="RIGHT" />
      <xs:enumeration value="BOTTOM" />
      <xs:enumeration value="H_CENTER" />
      <xs:enumeration value="V_CENTER" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TilingType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NONE" />
      <xs:enumeration value="HORZ" />
      <xs:enumeration value="VERT" />
      <xs:enumeration value="BOTH" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HorzAlignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LEFT" />
      <xs:enumeration value="CENTER" />
      <xs:enumeration value="RIGHT" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="VertAlignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TOP" />
      <xs:enumeration value="CENTER" />
      <xs:enumeration value="BOTTOM" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ScriptFileType">
    <xs:attribute name="file" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ScriptBlockType">
    <xs:simpleContent>
      <xs:extension base="xs:string" />
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="FontType">
    <xs:attribute name="name" use="required" type="xs:string" />
    <xs:attribute name="file" use="required" type="xs:string" />
    <xs:attribute name="size" use="required" type="xs:decimal" />
    <xs:attribute name="outline" use="optional" type="xs:decimal" />
    <xs:attribute name="shadowX" use="optional" type="xs:decimal" />
    <xs:attribute name="shadowY" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="PropertyType">
    <xs:attribute name="name" use="required" type="xs:string" />
    <xs:attribute name="value" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="PropertyValueType">
    <xs:attribute name="property" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="InsetType">
    <xs:attribute name="all" use="optional" type="xs:decimal" />
    <xs:attribute name="left" use="optional" type="xs:decimal" />
    <xs:attribute name="top" use="optional" type="xs:decimal" />
    <xs:attribute name="right" use="optional" type="xs:decimal" />
    <xs:attribute name="bottom" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="AreaComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Inset" type="InsetType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="BorderComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="texture" use="required" type="xs:string" />
    <xs:attribute name="borderSize" use="optional" type="xs:decimal" />
    <xs:attribute name="topSize" use="optional" type="xs:decimal" />
    <xs:attribute name="leftSize" use="optional" type="xs:decimal" />
    <xs:attribute name="rightSize" use="optional" type="xs:decimal" />
    <xs:attribute name="bottomSize" use="optional" type="xs:decimal" />
    <xs:attribute name="tint" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ImageComponentType">
    <xs:sequence minOccurs="0" maxOccurs="2">
      <xs:choice>
        <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
        <xs:element name="PropertyValue" type="PropertyValueType" minOccurs="0" maxOccurs="1" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="texture" use="optional" type="xs:string" />
    <xs:attribute name="tint" use="optional" type="xs:string" />
    <xs:attribute name="tiling" use="optional" type="TilingType" />
  </xs:complexType>

  <xs:complexType name="TextComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="color" use="optional" type="xs:string" />
    <xs:attribute name="horzAlign" use="optional" type="HorzAlignType" />
    <xs:attribute name="vertAlign" use="optional" type="VertAlignType" />
    <xs:attribute name="wrap" use="optional" type="xs:boolean" />
  </xs:complexType>

  <xs:complexType name="ImagerySectionType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="BorderComponent" type="BorderComponentType" />
        <xs:element name="ImageComponent" type="ImageComponentType" />
        <xs:element name="TextComponent" type="TextComponentType" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="SectionType">
    <xs:attribute name="section" use="required" type="xs:string" />
    <xs:attribute name="color" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="LayerType">
    <xs:sequence>
      <xs:element name="Section" maxOccurs="unbounded" minOccurs="1" type="SectionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="StateImageryType">
    <xs:sequence>
      <xs:element name="Layer" type="LayerType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="VisualType">
    <xs:sequence minOccurs="0">
      <xs:choice maxOccurs="unbounded">
        <xs:element name="ImagerySection" type="ImagerySectionType" />
        <xs:element name="StateImagery" type="StateImageryType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AbsDimensionType">
    <xs:attribute name="x" use="optional" type="xs:decimal" />
    <xs:attribute name="y" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="SizeType">
    <xs:sequence>
      <xs:element name="AbsDimension" type="AbsDimensionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PositionType">
    <xs:sequence>
      <xs:element name="AbsDimension" type="AbsDimensionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AnchorType">
    <xs:attribute name="point" use="required" type="AnchorPointType" />
    <xs:attribute name="relativePoint" use="optional" type="AnchorPointType" />
    <xs:attribute name="relativeTo" use="optional" type="xs:string" />
    <xs:attribute name="offset" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="AreaType">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Size" type="SizeType" />
        <xs:element name="Position" type="PositionType" />
        <xs:element name="Anchor" type="AnchorType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="EventsType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:any processContents="lax" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ScriptsType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="OnClick" type="ScriptBlockType" />
      <xs:element name="OnLoad" type="ScriptBlockType" />
      <xs:element name="OnUpdate" type="ScriptBlockType" />
      <xs:element name="OnTabPressed" type="ScriptBlockType" />
      <xs:element name="OnEnterPressed" type="ScriptBlockType" />
      <xs:element name="OnSpacePressed" type="ScriptBlockType" />
      <xs:element name="OnEscapePressed" type="ScriptBlockType" />
      <xs:element name="OnTextChanged" type="ScriptBlockType" />
      <xs:element name="OnShow" type="ScriptBlockType" />
      <xs:element name="OnHide" type="ScriptBlockType" />
      <xs:element name="OnEnter" type="ScriptBlockType" />
      <xs:element name="OnLeave" type="ScriptBlockType" />
      <xs:element name="OnDrag" type="ScriptBlockType" />
      <xs:element name="OnDrop" type="ScriptBlockType" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="FrameType">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Property" type="PropertyType" />
        <xs:element name="Visual" type="VisualType" />
        <xs:element name="Area" type="AreaType" />
        <xs:element name="Events" type="EventsType" />
        <xs:element name="Scripts" type="ScriptsType" />
        <xs:element name="Frame" type="FrameType" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="type" type="xs:string" use="optional" />
    <xs:attribute name="renderer" type="FrameRendererType" use="optional" />
    <xs:attribute name="inherits" type="xs:string" use="optional" />
    <xs:attribute name="parent" type="xs:string" use="optional" />
    <xs:attribute name="setAllPoints" type="xs:boolean" use="optional" />
    <xs:attribute name="id" type="xs:int" use="optional" />
  </xs:complexType>

  <xs:element name="Frame" type="FrameType" />

  <xs:element name="UiLayout">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Script" minOccurs="0" maxOccurs="unbounded" type="ScriptFileType" />
        <xs:element name="Font" minOccurs="0" maxOccurs="unbounded" type="FontType" />
        <xs:element ref="Frame" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Kyoril/mmo-data/Interface/GameUI/TargetFrame.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="TargetFrame.lua" />
	<Frame name="TargetFrame" parent="GameParent" renderer="DefaultRenderer">
		<Area>
			<Size>
				<AbsDimension x="560" y="176" />
			</Size>
			<Anchor point="LEFT" offset="360" relativePoint="H_CENTER" />
			<Anchor point="TOP" offset="0" relativeTo="PlayerFrame" />
		</Area>
		<Visual>
			<ImagerySection name="Background">
				<BorderComponent texture="Interface/GameUI/fg4_gradientBlackCircle2.htex" borderSize="31" tint="81FFFFFF" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
			<StateImagery name="Disabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
		</Visual>
		<Frame name="TargetPortrait" renderer="DefaultRenderer">
			<Area>
				<Size>
					<AbsDimension x="136" y="136" />
				</Size>
				<Anchor point="TOP" offset="8" />
				<Anchor point="RIGHT" offset="-8" />
			</Area>
			<Visual>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/GameUI/fg4_slotBrownRound1_result.htex" borderSize="36" tint="FFFFFFFF" />
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
			</Visual>
			<Frame name="TargetPortraitModel" type="UnitModel" renderer="ModelRenderer">
				<Property name="Animation" value="Idle" />
				<Property name="Yaw" value="-90" />
				<Property name="Portrait" value="true" />
				<Area>
					<Anchor point="TOP" offset="16" />
					<Anchor point="LEFT" offset="16" />
					<Anchor point="RIGHT" offset="-16" />
					<Anchor point="BOTTOM" offset="-16" />
				</Area>
			</Frame>
			<Frame name="TargetPortraitLevel" renderer="DefaultRenderer">
				<Property name="Font" value="CombatHudTextFont" />
				<Property name="TextColor" value="FFFFFFFF" />
				<Visual>
					<ImagerySection name="Background">
						<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlackSmall.htex" borderSize="11" tint="FFB6A890" />
						<TextComponent color="$TextColor" horzAlign="CENTER" vertAlign="CENTER" />
					</ImagerySection>
					<StateImagery name="Enabled">
						<Layer>
							<Section section="Background" />
						</Layer>
					</StateImagery>
					<StateImagery name="Disabled">
						<Layer>
							<Section section="Background" />
						</Layer>
					</StateImagery>
				</Visual>
				<Area>
					<Size>
						<AbsDimension x="64" y="40" />
					</Size>
					<Anchor point="H_CENTER" offset="0" />
					<Anchor point="BOTTOM" offset="18" />
				</Area>
			</Frame>
		</Frame>
		<Frame name="TargetName" inherits="TextSmall">
			<Property name="TextColor" value="FFF0E7D6" />
			<Property name="Font" value="CombatHudNameFont" />
			<Property name="HorzAlign" value="RIGHT" />
			<Area>
				<Size>
					<AbsDimension y="42" />
				</Size>
				<Anchor point="LEFT" offset="8" />
				<Anchor point="RIGHT" offset="-16" relativeTo="TargetPortrait" relativePoint="LEFT" />
				<Anchor point="TOP" offset="4" />
			</Area>
		</Frame>
		<Frame name="TargetHealthBar" type="ProgressBar">
			<Property name="Progress" value="0.12783" />
			<Property name="Font" value="CombatHudTextFont" />
			<Area>
				<Size>
					<AbsDimension y="60" />
				</Size>
				<Anchor point="LEFT" offset="8" />
				<Anchor point="RIGHT" offset="-16" relativeTo="TargetPortrait" relativePoint="LEFT" />
				<Anchor point="TOP" offset="0" relativeTo="TargetName" relativePoint="BOTTOM" />
			</Area>
			<Visual>
				<ImagerySection name="Caption">
					<TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
				</ImagerySection>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/fg4_borders_01_33.htex" borderSize="5" />
				</ImagerySection>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlackSmall.htex" borderSize="11" tint="FFB6A890" />
				</ImagerySection>
				<ImagerySection name="Progress">
					<ImageComponent texture="Interface/fg4_gradientWhiteV1_result.htex" tiling="HORZ" tint="FF43C653">
						<Area>
							<Inset all="8" />
						</Area>
					</ImageComponent>
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Progress">
					<Layer>
						<Section section="Progress" />
					</Layer>
				</StateImagery>
				<StateImagery name="Overlay">
					<Layer>
						<Section section="Border" />
						<Section section="Caption" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>
		<Frame name="TargetManaBar" type="ProgressBar">
			<Property name="Progress" value="0.12783" />
			<Property name="Font" value="CombatHudTextFont" />
			<Area>
				<Size>
					<AbsDimension y="44" />
				</Size>
				<Anchor point="LEFT" offset="8" />
				<Anchor point="RIGHT" offset="-16" relativeTo="TargetPortrait" relativePoint="LEFT" />
				<Anchor point="TOP" offset="6" relativeTo="TargetHealthBar" relativePoint="BOTTOM" />
			</Area>
			<Visual>
				<ImagerySection name="Caption">
					<TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
				</ImagerySection>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/fg4_borders_01_33.htex" borderSize="5" />
				</ImagerySection>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlackSmall.htex" borderSize="11" tint="FFB6A890" />
				</ImagerySection>
				<ImagerySection name="Progress">
					<ImageComponent texture="Interface/fg4_gradientWhiteV1_result.htex" tiling="HORZ" tint="FFFFFFFF">
						<Area>
							<Inset all="8" />
						</Area>
					</ImageComponent>
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Progress">
					<Layer>
						<Section section="Progress" />
					</Layer>
				</StateImagery>
				<StateImagery name="Overlay">
					<Layer>
						<Section section="Border" />
						<Section section="Caption" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>
		<Frame name="TargetFrameClick" setAllPoints="true">
			<Property name="HoverUnit" value="target" />
			<Scripts>
				<OnClick>
					return function(self, button)
						local pos = GetCursorPosition()
						TargetFrame_OnClick(TargetFrame, button, pos.x, pos.y)
					end
				</OnClick>
			</Scripts>
		</Frame>
		<Scripts>
			<OnLoad>
				return function(this)
					TargetFrame_OnLoad();
				end
			</OnLoad>
		</Scripts>
	</Frame>
	<!-- Target debuff icons live in their own frame below TargetFrame: hover hit-testing only
	     descends into children that lie inside their parent's rect, so as children of TargetFrame
	     (whose rect ends above them) the icons never received OnEnter and showed no tooltip. -->
	<Frame name="TargetAuraFrame" parent="GameParent">
		<Area>
			<Size>
				<AbsDimension x="392" y="80" />
			</Size>
			<Anchor point="LEFT" offset="0" relativeTo="TargetFrame" />
			<Anchor point="TOP" offset="0" relativeTo="TargetFrame" relativePoint="BOTTOM" />
		</Area>
		<Frame name="TargetAuraButton1" inherits="AuraBarButtonTemplate" id="1">
			<Area>
				<Size>
					<AbsDimension x="72" y="72" />
				</Size>
				<Anchor point="LEFT" offset="8" />
				<Anchor point="TOP" offset="8" />
			</Area>
		</Frame>
		<Frame name="TargetAuraButton2" inherits="AuraBarButtonTemplate" id="2">
			<Area>
				<Size>
					<AbsDimension x="72" y="72" />
				</Size>
				<Anchor point="LEFT" offset="6" relativeTo="TargetAuraButton1" relativePoint="RIGHT" />
				<Anchor point="TOP" offset="0" relativeTo="TargetAuraButton1" relativePoint="TOP" />
			</Area>
		</Frame>
		<Frame name="TargetAuraButton3" inherits="AuraBarButtonTemplate" id="3">
			<Area>
				<Size>
					<AbsDimension x="72" y="72" />
				</Size>
				<Anchor point="LEFT" offset="6" relativeTo="TargetAuraButton2" relativePoint="RIGHT" />
				<Anchor point="TOP" offset="0" relativeTo="TargetAuraButton1" relativePoint="TOP" />
			</Area>
		</Frame>
		<Frame name="TargetAuraButton4" inherits="AuraBarButtonTemplate" id="4">
			<Area>
				<Size>
					<AbsDimension x="72" y="72" />
				</Size>
				<Anchor point="LEFT" offset="6" relativeTo="TargetAuraButton3" relativePoint="RIGHT" />
				<Anchor point="TOP" offset="0" relativeTo="TargetAuraButton1" relativePoint="TOP" />
			</Area>
		</Frame>
		<Frame name="TargetAuraButton5" inherits="AuraBarButtonTemplate" id="5">
			<Area>
				<Size>
					<AbsDimension x="72" y="72" />
				</Size>
				<Anchor point="LEFT" offset="6" relativeTo="TargetAuraButton4" relativePoint="RIGHT" />
				<Anchor point="TOP" offset="0" relativeTo="TargetAuraButton1" relativePoint="TOP" />
			</Area>
		</Frame>
	</Frame>
</UiLayout>

=== Kyoril/mmo-data/Interface/GameUI/Minimap.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="Minimap.lua" />
	<Font name="MinimapCompassFont" file="Fonts/FRIZQT__.TTF" size="26" outline="2" shadowX="1.0" shadowY="1.0" />
	<Frame name="Minimap" parent="GameParent">
		<Scripts>
			<OnLoad>
				return function(self)
					Minimap_OnLoad(self);
				end
			</OnLoad>
			<OnShow>
				return function(self)
					Minimap_OnShow(self);
				end
			</OnShow>
			<OnHide>
				return function(self)
					Minimap_OnHide(self);
				end
			</OnHide>
		</Scripts>
		<Area>
			<Size>
				<AbsDimension x="384" y="512" />
			</Size>
			<Anchor point="RIGHT" offset="-24" />
			<Anchor point="TOP" offset="24" />
		</Area>
		<Frame name="MinimapTitleBar" renderer="DefaultRenderer">
			<Property name="Font" value="SmallLabelFont" />
			<Area>
				<Size>
					<AbsDimension y="56" />
				</Size>
				<Anchor point="LEFT" offset="0" />
				<Anchor point="RIGHT" offset="0" />
				<Anchor point="TOP" offset="0" />
			</Area>
			<Visual>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/GameUI/Alestia/WindowPanel.htex" borderSize="24" />
					<TextComponent color="FFF0E7D6" horzAlign="CENTER" vertAlign="CENTER">
						<Area>
							<Inset all="0" left="16" right="60" />
						</Area>
					</TextComponent>
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
			</Visual>
			<Frame name="MinimapCloseButton" inherits="IconButton">
				<Property name="Icon" value="Interface/Icons/fg4_iconsGold_close_result.htex" />
				<Area>
					<Size>
						<AbsDimension x="56" y="56" />
					</Size>
					<Anchor point="TOP" offset="0" />
					<Anchor point="RIGHT" offset="0" />
				</Area>
				<Scripts>
					<OnClick>
                        return function(self, button)
                            Minimap_Toggle(self);
                        end
                    </OnClick>
				</Scripts>
			</Frame>
		</Frame>
		<Frame name="MinimapContent" parent="GameParent" type="Minimap">
			<Area>
				<Size>
					<AbsDimension x="384" y="384" />
				</Size>
				<Anchor point="RIGHT" offset="0" relativeTo="Minimap" relativePoint="RIGHT" />
				<Anchor point="TOP" offset="8" relativeTo="MinimapTitleBar" relativePoint="BOTTOM" />
			</Area>
			<Frame name="MinimapBorder" renderer="DefaultRenderer">
				<Visual>
					<ImagerySection name="Background">
						<ImageComponent texture="Interface/GameUI/fg4_glass_border_result.htex" tiling="NONE" />
					</ImagerySection>
					<StateImagery name="Enabled">
						<Layer>
							<Section section="Background" />
						</Layer>
					</StateImagery>
				</Visual>
				<Area>
					<Anchor point="LEFT" offset="0" />
					<Anchor point="RIGHT" offset="0" />
					<Anchor point="TOP" offset="0" />
					<Anchor point="BOTTOM" offset="0" />
				</Area>
				<Scripts>
					<OnEnter>
                        return function(self)
                            MinimapContent_mouseOver = true;
                        end
                    </OnEnter>
					<OnLeave>
                        return function(self)
                            MinimapContent_mouseOver = false;
                            GameTooltip:Hide();
                        end
                    </OnLeave>
					<OnUpdate>
                        return function(self, delta)
                            Minimap_OnUpdate(self, delta);
                        end
                    </OnUpdate>
				</Scripts>
			</Frame>
			<!-- Compass letters follow the fixed north-up map and pass mouse input through. -->
			<Frame name="MinimapCompassNorth" inherits="TextSmall">
				<Property name="Text" value="MINIMAP_COMPASS_NORTH" />
				<Property name="Font" value="MinimapCompassFont" />
				<Property name="TextColor" value="FFEED37C" />
				<Property name="HorzAlign" value="CENTER" />
				<Property name="VertAlign" value="CENTER" />
				<Property name="Clickable" value="false" />
				<Property name="MousePassThrough" value="true" />
				<Area>
					<Size><AbsDimension x="36" y="36" /></Size>
					<Anchor point="TOP" offset="0" />
					<Anchor point="H_CENTER" offset="0" />
				</Area>
			</Frame>
			<Frame name="MinimapCompassEast" inherits="TextSmall">
				<Property name="Text" value="MINIMAP_COMPASS_EAST" />
				<Property name="Font" value="MinimapCompassFont" />
				<Property name="TextColor" value="FFF0E7D6" />
				<Property name="HorzAlign" value="CENTER" />
				<Property name="VertAlign" value="CENTER" />
				<Property name="Clickable" value="false" />
				<Property name="MousePassThrough" value="true" />
				<Area>
					<Size><AbsDimension x="36" y="36" /></Size>
					<Anchor point="RIGHT" offset="0" />
					<Anchor point="V_CENTER" offset="0" />
				</Area>
			</Frame>
			<Frame name="MinimapCompassSouth" inherits="TextSmall">
				<Property name="Text" value="MINIMAP_COMPASS_SOUTH" />
				<Property name="Font" value="MinimapCompassFont" />
				<Property name="TextColor" value="FFF0E7D6" />
				<Property name="HorzAlign" value="CENTER" />
				<Property name="VertAlign" value="CENTER" />
				<Property name="Clickable" value="false" />
				<Property name="MousePassThrough" value="true" />
				<Area>
					<Size><AbsDimension x="36" y="36" /></Size>
					<Anchor point="BOTTOM" offset="0" />
					<Anchor point="H_CENTER" offset="0" />
				</Area>
			</Frame>
			<Frame name="MinimapCompassWest" inherits="TextSmall">
				<Property name="Text" value="MINIMAP_COMPASS_WEST" />
				<Property name="Font" value="MinimapCompassFont" />
				<Property name="TextColor" value="FFF0E7D6" />
				<Property name="HorzAlign" value="CENTER" />
				<Property name="VertAlign" value="CENTER" />
				<Property name="Clickable" value="false" />
				<Property name="MousePassThrough" value="true" />
				<Area>
					<Size><AbsDimension x="36" y="36" /></Size>
					<Anchor point="LEFT" offset="0" />
					<Anchor point="V_CENTER" offset="0" />
				</Area>
			</Frame>
			<Frame name="MinimapZoomIn" inherits="RoundIconButton">
				<Property name="Icon" value="Interface/Icons/fg4_iconsBrown_plus_result.htex" />
				<Area>
					<Anchor point="RIGHT" offset="0" />
					<Anchor point="BOTTOM" offset="-64" />
				</Area>
				<Scripts>
					<OnClick>
                        return function(self, button)
                            SetMinimapZoomLevel(GetMinimapZoomLevel() + 1);
                            Minimap_OnZoomChanged();
                        end
                    </OnClick>
				</Scripts>
			</Frame>
			<Frame name="MinimapZoomOut" inherits="RoundIconButton">
				<Property name="Icon" value="Interface/Icons/fg4_iconsBrown_minus_result.htex" />
				<Area>
					<Anchor point="RIGHT" offset="-64" />
					<Anchor point="BOTTOM" offset="0" />
				</Area>
				<Scripts>
					<OnClick>
                        return function(self, button)
                            SetMinimapZoomLevel(GetMinimapZoomLevel() - 1);
                            Minimap_OnZoomChanged();
                        end
                    </OnClick>
				</Scripts>
			</Frame>
			<Frame name="MinimapDayNight" inherits="RoundIconButton">
				<Property name="Icon" />
				<Area>
					<Anchor point="RIGHT" offset="0" />
					<Anchor point="TOP" offset="0" />
					<Size>
						<AbsDimension x="96" y="96" />
					</Size>
				</Area>
			</Frame>
		</Frame>
		<Frame name="MinimapTime" inherits="TextSmall">
			<Property name="Clickable" value="false" />
			<Property name="VertAlign" value="CENTER" />
			<Property name="TextColor" value="FFE2DCCD" />
			<Property name="Font" value="SmallLabelFont" />
			<Property name="HorzAlign" value="CENTER" />
			<Area>
				<Size>
					<AbsDimension x="160" y="40" />
				</Size>
				<Anchor point="H_CENTER" offset="0" relativeTo="Minimap" relativePoint="H_CENTER" />
				<Anchor point="TOP" offset="8" relativeTo="MinimapContent" relativePoint="BOTTOM" />
			</Area>
			<Scripts>
				<OnUpdate>
                        return function(self, delta)
                            Minimap_UpdateTime();
                        end
                    </OnUpdate>
			</Scripts>
		</Frame>
	</Frame>
</UiLayout>
